### ISSUE TITLE
Open the kernel memory case cgroup memory leak 

### ISSUE THREAD

**Issue by cgzchen** [tkestack/tke#175]
**What happened**:
I download tke offline installer. 
I see installer has docker-ce 17.03 and kubelet v1.16.6 (default)

My Environment is centos7 3.10(kernel); In my Environment, it will cgroup memory leak, application crash, or  SLUB allocated memory failed

 **I want**
docker 18.09
kubelet rebuild by "nomem" tag

**Environment**:

- TKE version:
version=v1.1.0 && wget https://tke-release-1251707795.cos.ap-guangzhou.myqcloud.com/tke-installer-x86_64-$version.run{,.sha256} && sha256sum --check --status tke-installer-x86_64-$version.run.sha256 && chmod +x tke-installer-x86_64-$version.run && ./tke-installer-x86_64-$version.run

- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by choujimmy** [comment]
Thanks for your feedback, here are two things to explain:
1) The docker version of the installer is not 17.03. The reason you see that is because the installer will detect whether the docker is already installed on the machine. If there is a docker installed on tkestack, it is your 17.03 Docker already installed on.
2)The goal of tkestack is not to make a kubernetes distribution. Based on this, we will not magically change the source code of kubernetes. This cgroup leak problem is recommended to refer [this issue](https://github.com/docker/for-linux/issues/841), add `cgroup.memory=nokmem` to kernel startup parameters.
