### ISSUE TITLE
Support incremental compilation and incremental installation

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tke#32]
**incremental compilation**
when I use `make release` to build the installer image, it will cost duplicative effort to generate the `images.tar.gz`, even the file already exist.

**incremental installation**
each time when I start a new installation, tke-installer always load the image.tar.gz, no matter if i have done this before.
```log
root     16070 16052  0 15:48 ?        00:00:00 /app/bin/tke-installer
root     16187 16070  3 15:49 ?        00:00:00 docker load -i images.tar.gz
root     16197  5766 12 15:49 ?        00:00:01 docker-untar / /var/lib/docker/tmp/docker-import-404992003
```

**Comment by QianChenglong** [comment]
incremental compilation
1.hard to ensure current images.tar.gz is we want because dependenies is complicated.
2.in out ci release, no place to store cache
3.for cache, it's inplement cost is too expensive.
In summary, implementation is not considered for the time being
incremental installation
New installation is new installation.
Introducing too many caches, the implementation is too complicated, and the benefit is not high for the time being, because the real user scenario will not be completely restarted. Our installer can resume execution abnormally.

**Comment by ruyingzhe** [comment]
The building of TKE cost too much time, storage and traffic each time,  I hope we can optimize the building process, avoid the duplicate operation, add checksum to save the build time.

before the installation start, tke-installer run `docker load -i images.tar.gz ` everytime, I think there should be a checker, to check if the images are already loaded, if yes, skip the `docker load ` operation.
