### ISSUE TITLE
HA config for master host list failed on UI validation

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#659]
for tke provide ha support, when you set master as `10.0.0.127;10.0.0.197;10.0.0.9`,  it failed after click `install` on UI and show below error message:
```
invalid IP address: 10.0.0.127;10.0.0.197;10.0.0.9
```

to workaround,  you have to add master host one by one.

**Comment by johnny19941216** [comment]
this is because install will be call api '/api/ssh', but this api not support host string split for  `;`
![image](https://user-images.githubusercontent.com/15609400/92443925-c5b48100-f1e4-11ea-9edb-62d400f7b082.png)
![image](https://user-images.githubusercontent.com/15609400/92443967-d1a04300-f1e4-11ea-9632-a90405ec47b9.png)

**Comment by huxiaoliang** [comment]
@johnny19941216  back-end don't have logic to split  the host string by ";"  please double check fronted. I think this case should same as ui add host one by one.
